spring:
  datasource:
    username: electrical_machine
    password: electrical_machine
    url: jdbc:mysql://localhost:3306/electrical_machine
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true